# Generated by Django 2.0 on 2017-12-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='shortcode',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
