# Generated by Django 3.0.7 on 2020-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsagree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='content_nb',
            field=models.TextField(blank=True, verbose_name='Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='term',
            name='summary_nb',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='term',
            name='title_nb',
            field=models.CharField(blank=True, db_index=True, max_length=63, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='term',
            name='content_en',
            field=models.TextField(verbose_name='Terms and Conditions'),
        ),
        migrations.AlterField(
            model_name='term',
            name='summary_en',
            field=models.TextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='term',
            name='title_en',
            field=models.CharField(db_index=True, max_length=63, verbose_name='Title'),
        ),
    ]
