# Generated by Django 2.0.7 on 2018-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mealplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='pdf',
            field=models.FileField(upload_to='menus/'),
        ),
    ]
