# Generated by Django 2.0.7 on 2018-11-29 16:47

from django.db import migrations, models
import helper


class Migration(migrations.Migration):
    dependencies = [
        ('mealplan', '0002_auto_20181129_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='pdf',
            field=models.FileField(upload_to=helper.path_and_rename),
        ),
    ]
