# Generated by Django 2.0.7 on 2018-12-11 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mealplan', '0003_auto_20181129_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('calendar_week', 'year')},
        ),
    ]
