# Generated by Django 2.0 on 2017-12-19 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0006_auto_20171219_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 20, 22, 55, 889224)),
        ),
    ]
