# Generated by Django 2.0 on 2017-12-20 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0010_auto_20171220_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 12, 36, 26, 622305)),
        ),
    ]
