# Generated by Django 2.0 on 2017-12-20 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0011_auto_20171220_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 20, 26, 25, 628258)),
        ),
    ]
