# Generated by Django 2.0 on 2017-12-20 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0012_auto_20171220_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 28, 55, 417477, tzinfo=utc)),
        ),
    ]
