# Generated by Django 2.0 on 2017-12-20 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0013_auto_20171220_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 29, 36, 159739, tzinfo=utc)),
        ),
    ]
