# Generated by Django 2.0 on 2017-12-20 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0014_auto_20171220_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 41, 56, 561328, tzinfo=utc)),
        ),
    ]
