# Generated by Django 2.2.1 on 2019-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id',
                 models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('expiration_time', models.IntegerField(default=20, verbose_name='Ablaufzeit')),
            ],
            options={
                'verbose_name': 'Cacheeintrag',
                'verbose_name_plural': 'Cacheeinträge',
            },
        ),
    ]
