# Generated by Django 2.2.1 on 2019-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='last_time_updated',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='Letzter Aktualisierungszeitpunkt des Caches'),
        ),
    ]
