# Generated by Django 2.2.1 on 2019-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0003_cache_last_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='site_cache',
            field=models.BooleanField(default=False, verbose_name='Seitencache?'),
        ),
    ]
