# Generated by Django 2.2.6 on 2019-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0004_cache_site_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='needed_until',
            field=models.DateField(default=None, null=True, verbose_name='Benötigt bis'),
        ),
    ]
