# Generated by Django 2.2.6 on 2019-11-18 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_cache_needed_until'),
        ('dashboard', '0002_notification_read'),
    ]

    operations = [
    ]
