# Generated by Django 2.2.1 on 2019-05-23 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebugLogGroup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('desc_as_pre',
                 models.CharField(blank=True, max_length=250, verbose_name='Beschreibung, dargestellt als HTML-PRE')),
            ],
            options={
                'verbose_name': 'Debug-Log-Gruppe',
                'verbose_name_plural': 'Debug-Log-Gruppen',
            },
        ),
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='UNIX-Rückgabecode')),
                ('filename', models.FilePathField(match='.*.log', path='/home/wethjo/dev/school-apps/schoolapps/latex',
                                                  verbose_name='Dateiname zur Logdatei')),
                ('updated_at',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aktualisierungszeitpunkt')),
                ('group',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='logs', to='debug.DebugLogGroup', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Debug-Log',
                'verbose_name_plural': 'Debug-Logs',
            },
        ),
    ]
