# Generated by Django 2.2.1 on 2019-05-29 15:05

from django.db import migrations, models
import utils.helper as helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_week', models.IntegerField(verbose_name='KW')),
                ('year', models.IntegerField(verbose_name='Jahr')),
                ('pdf', models.FileField(upload_to=helper.path_and_rename, verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Speiseplan',
                'verbose_name_plural': 'Speisepläne',
                'unique_together': {('calendar_week', 'year')},
            },
        ),
    ]
