# Generated by Django 2.0.7 on 2018-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pdf', models.FileField(upload_to='mealplan/%Y/')),
            ],
        ),
    ]
