# Generated by Django 2.0.7 on 2018-12-11 16:43

from django.db import migrations, models
import helper


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0004_auto_20181211_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_week', models.IntegerField(verbose_name='KW')),
                ('year', models.IntegerField(verbose_name='Jahr')),
                ('pdf', models.FileField(upload_to=helper.path_and_rename, verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Speiseplan',
                'verbose_name_plural': 'Speisepläne',
            },
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('calendar_week', 'year')},
        ),
    ]
