# Generated by Django 2.1.5 on 2019-04-10 12:30

import datetime
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('untisconnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Startdatum')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Enddatum')),
                ('text', martor.models.MartorField(verbose_name='Hinweistext')),
            ],
            options={
                'verbose_name': 'Hinweis',
                'verbose_name_plural': 'Hinweise',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('show_plan', 'Show plan'),),
            },
        ),
    ]
