# Generated by Django 2.0.3 on 2018-04-10 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='room',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
