# Generated by Django 2.1.5 on 2019-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
            ],
        ),
    ]
