# Generated by Django 2.2 on 2019-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0004_auto_20190411_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='hints', to='timetable.HintClass',
                                         verbose_name='Klassen'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='teachers',
            field=models.BooleanField(blank=True, default=False, verbose_name='Lehrer?'),
        ),
    ]
