# Generated by Django 2.2.1 on 2019-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0005_auto_20190413_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='text_as_latex',
            field=models.TextField(blank=True, verbose_name='LaTeX (automatisch)'),
        ),
    ]
