# Generated by Django 2.2.1 on 2019-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0006_hint_text_as_latex'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintclass',
            name='class_name',
            field=models.CharField(default='…', max_length=100),
        ),
    ]
