# Generated by Django 2.2.1 on 2019-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0007_hintclass_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hintclass',
            old_name='class_name',
            new_name='name',
        ),
    ]
