# Generated by Django 2.2.1 on 2019-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0008_auto_20190502_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='classes_formatted',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
