# Generated by Django 2.2.1 on 2019-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_hint_classes_formatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hintclass',
            name='class_id',
            field=models.IntegerField(),
        ),
    ]
