# Generated by Django 2.2.1 on 2019-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0009_hint_classes_formatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hintclass',
            name='class_id',
            field=models.IntegerField(),
        ),
    ]
