# Generated by Django 2.2.1 on 2019-05-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0010_debugloggroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='UNIX-Rückgabecode')),
                ('filename', models.FilePathField(match='*.log', path='/home/wethjo/dev/school-apps/schoolapps/latex',
                                                  verbose_name='Dateiname zur Logdatei')),
                ('group',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='logs', to='timetable.DebugLogGroup', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Debug-Log',
                'verbose_name_plural': 'Debug-Logs',
            },
        ),
    ]
