# Generated by Django 2.2.6 on 2019-11-13 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0010_auto_20190818_0910'),
        ('timetable', '0010_auto_20190825_1238'),
    ]

    operations = [
    ]
