# Generated by Django 2.2.6 on 2019-11-18 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0011_merge_20191113_1655'),
        ('timetable', '0010_auto_20190901_1040'),
    ]

    operations = [
    ]
