# Generated by Django 2.2.1 on 2019-05-22 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0012_auto_20190522_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuglog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 8, 10, 52079)),
        ),
    ]
