# Generated by Django 2.2.1 on 2019-05-22 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0013_auto_20190522_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuglog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 14, 8, 34, 95310, tzinfo=utc)),
        ),
    ]
