# Generated by Django 2.2.1 on 2019-05-22 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0014_auto_20190522_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuglog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
