# Generated by Django 2.2.1 on 2019-05-22 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0015_auto_20190522_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debugloggroup',
            options={'verbose_name': 'Debug-Log-Gruppe', 'verbose_name_plural': 'Debug-Log-Gruppen'},
        ),
        migrations.AlterField(
            model_name='debuglog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aktualisierungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='debugloggroup',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='debugloggroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
