# Generated by Django 2.2.5 on 2019-09-14 13:03

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='', verbose_name='School logo'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_cropping',
            field=image_cropping.fields.ImageRatioField('logo', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='logo cropping'),
        ),
    ]
