# Generated by Django 2.2.3 on 2019-07-15 21:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fill_person_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardians',
            field=models.ManyToManyField(related_name='children',
                                         to='core.Person', verbose_name='Guardians / Parents'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is person active?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name='Home phone'),
        ),
    ]
