# Generated by Django 2.2.8 on 2019-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_yubi_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolterm',
            name='school',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Long name of group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Short name of group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='import_ref',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Reference ID of import source'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Short name'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='school',
        ),
        migrations.RemoveField(
            model_name='person',
            name='school',
        ),
    ]
