# Generated by Django 2.2.3 on 2019-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Long name of group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(max_length=8, unique=True, verbose_name='Short name of group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='import_ref',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True, verbose_name='Reference ID of import source'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='Short name'),
        ),
    ]
