# Generated by Django 2.2.8 on 2019-12-09 21:04

from django.contrib.auth import get_user_model
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = get_user_model()

    if not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            username='admin',
            email='root@example.com',
            password='admin'
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unlink_school'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
