# Generated by Django 2.2.3 on 2019-07-30 21:02

import biscuit.core.util.core_helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AlterField(
            model_name='person',
            name='school',
            field=models.ForeignKey(default=biscuit.core.util.core_helpers.get_current_school, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
    ]
