# Generated by Django 2.2.4 on 2019-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_default_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='import_ref',
            field=models.CharField(blank=True, editable=False, max_length=64,
                                   null=True, verbose_name='Reference ID of import source'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Short name'),
        ),
    ]
