# Generated by Django 2.2.4 on 2019-08-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='primary_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Group'),
        ),
    ]
