# Generated by Django 2.2.4 on 2019-08-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_person_primary_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Long name of group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(max_length=8, verbose_name='Short name of group'),
        ),
    ]
