# Generated by Django 2.2.4 on 2019-08-29 12:12

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_cropping',
            field=image_cropping.fields.ImageRatioField('photo', '600x800', adapt_rotation=False, allow_fullsize=False,
                                                        free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo cropping'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=image_cropping.fields.ImageCropField(
                blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
