# Generated by Django 2.2.4 on 2019-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_person_photo_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent_groups',
            field=models.ManyToManyField(related_name='child_groups', to='core.Group', verbose_name='Parent groups'),
        ),
    ]
