# Generated by Django 2.1.2 on 2019-01-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(max_length=5),
        ),
    ]
