# Generated by Django 2.2.1 on 2019-05-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('debug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debuglog',
            name='log_text',
            field=models.TextField(blank=True, verbose_name='Log-Text (falls nicht Datei)'),
        ),
        migrations.AlterField(
            model_name='debuglog',
            name='filename',
            field=models.FilePathField(blank=True, match='.*.log', path='/home/wethjo/dev/school-apps/schoolapps/latex',
                                       verbose_name='Dateiname zur Logdatei (falls nicht Log-Text)'),
        ),
    ]
