# Generated by Django 2.2.4 on 2019-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0003_auto_20190818_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuglog',
            name='filename',
            field=models.FilePathField(blank=True, match='.*.log', path='/data/Silas/Daten/school-apps/schoolapps/latex', verbose_name='Dateiname zur Logdatei (falls nicht Log-Text)'),
        ),
    ]
