# Generated by Django 2.0.3 on 2018-04-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
    ]
