# Generated by Django 2.0.3 on 2018-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0003_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
