# Generated by Django 2.2.6 on 2019-12-28 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('fibu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('manage_account', 'Can manage account')], 'verbose_name': 'Buchungskonto',
                     'verbose_name_plural': 'Buchungskonten'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={
                'permissions': [('manage_booking', 'Can manage bookings'), ('request_booking', 'Can request a booking'),
                                ('check_booking', 'Can check bookings')], 'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'permissions': [('manage_costcenter', 'Can manage costcenter')], 'verbose_name': 'Kostenstelle',
                     'verbose_name_plural': 'Kostenstellen'},
        ),
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='account',
            name='costcenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibu.CostCenter',
                                    verbose_name='Kostenstelle'),
        ),
        migrations.AlterField(
            model_name='account',
            name='income',
            field=models.BooleanField(default=False, verbose_name='Einnahmekonto'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Buchungskonto'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maturity',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'beantragt'), (1, 'abgelehnt'), (2, 'bewilligt'), (3, 'bestellt'), (4, 'eingereicht'),
                         (5, 'bezahlt')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Kostenstelle'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='year',
            field=models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')],
                                      default=2019, verbose_name='Jahr'),
        ),
    ]
