# Generated by Django 2.2.8 on 2019-12-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibu', '0002_auto_20191228_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.IntegerField(default=0, verbose_name='Budget'),
        ),
    ]
