# Generated by Django 2.2.1 on 2019-05-29 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('icon', models.CharField(blank=True, default='question_answer', max_length=20)),
                ('show', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('answer_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FAQ-Frage',
                'verbose_name_plural': 'FAQ-Fragen',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('answered', models.BooleanField(default=False, verbose_name='Beantwortet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
    ]
