# Generated by Django 2.1.5 on 2019-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='icon',
            field=models.CharField(blank=True, default='question_answer', max_length=20),
        ),
    ]
