# Generated by Django 2.2.3 on 2019-07-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, default='question_answer', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Bei den Antworten funktioniert auch HTML-Syntax!<br> Aus Gründen des verwendeten CSS-Frameworks muss der Tag <strong>&lt;ul&gt;</strong> die CSS-Klasse <em>browser-default</em> besitzen!'),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='faq.FAQSection'),
            preserve_default=False,
        ),
    ]
