# Generated by Django 2.2.3 on 2019-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20190722_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqsection',
            options={'verbose_name': 'FAQ-Abschnitt', 'verbose_name_plural': 'FAQ-Abschnitte'},
        ),
        migrations.AddField(
            model_name='faqsection',
            name='icon_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('brown', 'brown'), ('grey', 'grey'), ('blue-grey', 'blue-grey'), ('black', 'black'), ('white', 'white'), ('transparent', 'transparent')], default='black', max_length=10),
        ),
    ]
