# Generated by Django 2.1.5 on 2019-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20190429_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqanswer',
            name='answer_text',
            field=models.TextField(),
        ),
    ]
