# Generated by Django 2.1.5 on 2019-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20190429_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='FAQAnswer',
        ),
    ]
