# Generated by Django 2.0.4 on 2018-04-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default=1, on_delete=models.SET(1), related_name='aubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('apply_for_aub', 'Apply for a AUB'), ('allow_aub', 'Allow a AUB'), ('check_aub', 'Check a AUB')),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style_classes', models.CharField(max_length=200)),
            ],
        ),
    ]
