# Generated by Django 2.0 on 2017-12-19 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aub',
            name='title',
        ),
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 20, 8, 50, 895634)),
        ),
    ]
