# Generated by Django 2.0 on 2017-12-20 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 28, 55, 416188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aub',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 19, 28, 55, 402477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aub',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 19, 28, 55, 402526, tzinfo=utc)),
        ),
    ]
