# Generated by Django 2.0 on 2017-12-21 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aub',
            name='x',
        ),
    ]
