# Generated by Django 2.1.2 on 2018-10-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='aubs', to='aub.Status'),
        ),
    ]
