# Generated by Django 2.0 on 2017-12-19 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0002_auto_20171219_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 20, 12, 38, 519024)),
        ),
    ]
