# Generated by Django 2.0 on 2017-12-21 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0002_remove_aub_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='aub',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aub',
            name='to_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aub',
            name='from_lesson',
            field=models.IntegerField(blank=True,
                                      choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)],
                                      default=1),
        ),
        migrations.AlterField(
            model_name='aub',
            name='to_lesson',
            field=models.IntegerField(blank=True,
                                      choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)],
                                      default=1),
        ),
    ]
