# Generated by Django 2.0 on 2017-12-20 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0002_auto_20171220_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 29, 36, 158500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aub',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 19, 29, 36, 145293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aub',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 19, 29, 36, 145343, tzinfo=utc)),
        ),
    ]
