# Generated by Django 2.1.2 on 2018-12-23 08:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0002_aub_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aub',
            name='from_dt',
        ),
        migrations.RemoveField(
            model_name='aub',
            name='to_dt',
        ),
        migrations.AddField(
            model_name='aub',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='aub',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aub',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='aub',
            name='to_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
