# Generated by Django 2.0 on 2017-12-22 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0003_auto_20171221_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aub',
            options={'permissions': (('apply_for_aub', 'Apply for a AUB'), ('allow_request', 'Allow a request'),
                                     ('check_request', 'Check a request'))},
        ),
    ]
