# Generated by Django 2.0 on 2017-12-19 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0003_auto_20171219_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 20, 13, 53, 644954)),
        ),
    ]
