# Generated by Django 2.0.4 on 2018-04-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0003_auto_20180410_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aub',
            options={'permissions': (('apply_for_aub', 'Apply for a AUB'), ('cancel_aub', 'Cancel a AUB'), ('allow1_aub', 'First permission'), ('allow2_aub', 'Second permission'), ('check1_aub', 'Check a AUB'), ('check2_aub', 'Check a AUB'))},
        ),
    ]
