# Generated by Django 2.0.7 on 2018-11-28 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0004_auto_20181031_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=models.SET(3), related_name='aubs',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
