# Generated by Django 2.0.3 on 2018-04-12 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0004_auto_20180411_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=models.SET(3), related_name='aubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=2, on_delete=models.SET(2), related_name='aubs', to='aub.Status'),
        ),
    ]
