# Generated by Django 2.0 on 2017-12-19 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teachers', '0003_auto_20171219_2013'),
        ('aub', '0004_auto_20171219_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aub',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='aub',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='aubs',
                                    to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 20, 22, 55, 888080)),
        ),
    ]
