# Generated by Django 2.0 on 2017-12-22 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0004_auto_20171222_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aub',
            options={'permissions': (
            ('apply_for_aub', 'Apply for a AUB'), ('allow_aub', 'Allow a AUB'), ('check_aub', 'Check a AUB'))},
        ),
    ]
