# Generated by Django 2.1.2 on 2018-12-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0005_auto_20181128_1709'),
        ('aub', '0003_auto_20181223_0905'),
    ]

    operations = [
    ]
