# Generated by Django 2.0.7 on 2019-01-06 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0003_auto_20181223_0905'),
        ('aub', '0005_auto_20181128_1709'),
    ]

    operations = [
    ]
