# Generated by Django 2.0 on 2017-12-22 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0005_auto_20171222_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aub',
            name='from_lesson',
        ),
        migrations.RemoveField(
            model_name='aub',
            name='to_lesson',
        ),
    ]
