# Generated by Django 2.1.5 on 2019-04-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0003_auto_20181223_0905'),
        ('aub', '0006_auto_20181219_1107'),
    ]

    operations = [
    ]
