# Generated by Django 2.0 on 2017-12-22 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0006_auto_20171222_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aub',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='aub',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='aub',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='aub',
            name='to_time',
        ),
        migrations.AddField(
            model_name='aub',
            name='from_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aub',
            name='to_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
