# Generated by Django 2.0.4 on 2019-01-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0006_auto_20181219_1107'),
        ('aub', '0006_merge_20190106_1714'),
    ]

    operations = [
    ]
