# Generated by Django 2.1.2 on 2019-02-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0006_merge_20181226_1733'),
        ('aub', '0006_merge_20190106_1714'),
    ]

    operations = [
    ]
