# Generated by Django 2.1.4 on 2019-01-02 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aub', '0007_auto_20190102_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='aub',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='aubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='aubs', to='aub.Status'),
        ),
    ]
