# Generated by Django 2.0 on 2017-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0007_auto_20171222_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style_classes', models.CharField(max_length=200)),
            ],
        ),
    ]
