# Generated by Django 2.0.4 on 2019-02-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0008_auto_20190211_1935'),
        ('aub', '0007_merge_20190118_1452'),
    ]

    operations = [
    ]
