# Generated by Django 2.0 on 2018-01-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0008_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=2, on_delete=models.SET(2), related_name='aubs', to='aub.Status'),
        ),
    ]
