# Generated by Django 2.0.4 on 2019-03-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0006_merge_20190102_1724'),
        ('aub', '0009_merge_20190222_1226'),
    ]

    operations = [
    ]
