# Generated by Django 2.0 on 2018-01-01 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0009_aub_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=models.SET(3), related_name='aubs',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
