# Generated by Django 2.1.2 on 2019-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0009_merge_20190222_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aub',
            options={'permissions': (('apply_for_aub', 'Apply for a AUB'), ('cancel_aub', 'Cancel a AUB'), ('allow1_aub', 'First permission'), ('allow2_aub', 'Second permission'), ('check1_aub', 'Check a AUB'), ('check2_aub', 'Check a AUB'), ('view_archive', 'View AUB archive'))},
        ),
        migrations.AlterField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='aubs', to='aub.Status'),
        ),
    ]
