# Generated by Django 2.1.5 on 2019-03-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0010_auto_20190304_1404'),
        ('aub', '0006_merge_20190102_1724'),
    ]

    operations = [
    ]
