# Generated by Django 2.1.2 on 2019-03-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0009_auto_20190111_1525'),
        ('aub', '0010_auto_20190304_1404'),
    ]

    operations = [
    ]
