# Generated by Django 2.1.7 on 2019-03-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0010_merge_20190310_1915'),
        ('aub', '0010_auto_20190304_1404'),
    ]

    operations = [
    ]
