# Generated by Django 2.1.2 on 2019-04-06 10:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aub', '0011_merge_20190318_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
