# Generated by Django 2.1.5 on 2019-04-10 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0011_merge_20190318_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=models.SET(3), related_name='aubs',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=5, on_delete=models.SET(5), related_name='aubs', to='aub.Status'),
        ),
    ]
