# Generated by Django 2.2 on 2019-04-25 18:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0011_merge_20190318_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aub',
            options={'permissions': (
            ('apply_for_aub', 'Apply for a AUB'), ('cancel_aub', 'Cancel a AUB'), ('allow1_aub', 'First permission'),
            ('allow2_aub', 'Second permission'), ('check1_aub', 'Check a AUB'), ('check2_aub', 'Check a AUB'),
            ('view_archive', 'View AUB archive')), 'verbose_name': 'AUB', 'verbose_name_plural': 'AUBs'},
        ),
        migrations.AlterField(
            model_name='aub',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=models.SET(3), related_name='aubs',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='from_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'In Bearbeitung 1'), (1, 'In Bearbeitung 2'), (2, 'Genehmigt'), (3, 'Abgelehnt')],
                default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='to_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='aub',
            name='to_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Endzeit'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
