# Generated by Django 2.2 on 2019-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aub', '0012_auto_20190410_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aub',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='aubs', to='aub.Status'),
        ),
    ]
