# Generated by Django 2.2.1 on 2019-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('use_rebus', 'Can use REBUS'), ('send_feedback', 'Can send feedback')),
            },
        ),
    ]
