# Generated by Django 2.1.5 on 2019-01-20 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'permissions': (('use_rebus', 'Can use REBUS'), ('send_feedback', 'Can send feedback'),
                                     ('can_edit_support_settings', 'Can edit support settings'))},
        ),
    ]
