# Generated by Django 3.1.2 on 2020-10-28 10:22

from django.db import migrations, models
import django.utils.timezone
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drop_image_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_cropping',
            field=image_cropping.fields.ImageRatioField('photo', '600x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo cropping'),
        ),
    ]
