# Generated by Django 3.0.2 on 2020-01-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_replace_user_by_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['short_name', 'name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name', 'name_official'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='schoolterm',
            options={'verbose_name': 'School term', 'verbose_name_plural': 'School terms'},
        ),
    ]
