# Generated by Django 3.1.6 on 2021-02-21 22:07

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_default_dashboard'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_activi_extende_9847a5_gin'),
        ),
        migrations.AddIndex(
            model_name='additionalfield',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_additi_extende_47ba24_gin'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_announ_extende_1f1b52_gin'),
        ),
        migrations.AddIndex(
            model_name='announcementrecipient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_announ_extende_d46f40_gin'),
        ),
        migrations.AddIndex(
            model_name='custommenu',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_custom_extende_58168d_gin'),
        ),
        migrations.AddIndex(
            model_name='custommenuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_custom_extende_620b86_gin'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidgetorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_dashbo_extende_67aae0_gin'),
        ),
        migrations.AddIndex(
            model_name='datacheckresult',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_datach_extende_f714a1_gin'),
        ),
        migrations.AddIndex(
            model_name='grouptype',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_groupt_extende_38008a_gin'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_notifi_extende_8bc050_gin'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_person_extende_32726c_gin'),
        ),
        migrations.AddIndex(
            model_name='persongroupthrough',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_person_extende_b3cf06_gin'),
        ),
        migrations.AddIndex(
            model_name='schoolterm',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extended_data'], name='core_school_extende_e8920d_gin'),
        ),
    ]
