# Generated by Django 3.0.2 on 2020-02-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dashboard_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='primary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Group'),
        ),
    ]
