# Generated by Django 3.0.3 on 2020-02-10 14:22

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_make_primary_group_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date and time from when to show')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Date and time until when to show')),
                ('recipient_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
