# Generated by Django 3.0.3 on 2020-02-20 12:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import aleksis.core.util.core_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='extended_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='extended_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='extended_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
    ]
