# Generated by Django 3.0.3 on 2020-02-19 18:14

import aleksis.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='recipient_id',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_until',
            field=models.DateTimeField(default=aleksis.core.models.now_tomorrow, verbose_name='Date and time until when to show'),
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.PositiveIntegerField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.Announcement')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcementrecipient',
            options={'verbose_name': 'Announcement recipient', 'verbose_name_plural': 'Announcement recipients'},
        ),
    ]
