# Generated by Django 3.0.3 on 2020-02-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_multiple_recipients_announcement'),
        ('core', '0013_extensible_model_as_default'),
    ]

    operations = [
    ]
