# Generated by Django 3.0.4 on 2020-03-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accouncement_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='import_ref',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Reference ID of import source'),
        ),
    ]
