# Generated by Django 3.0.3 on 2020-02-25 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_multiple_recipients_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrecipient',
            name='extended_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
    ]
