# Generated by Django 3.0.4 on 2020-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_custom_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Short name of group'),
        ),
    ]
