# Generated by Django 3.0.4 on 2020-03-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_make_group_short_name_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first', 'last'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='additional_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='first',
            field=models.CharField(blank=True, max_length=100, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='person',
            name='full',
            field=models.CharField(default='', max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(max_length=100, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
    ]
