# Generated by Django 3.0.4 on 2020-03-28 21:44

from django.db import migrations, models

def rewrite_names(apps, schema_editor)
    db_alias = schema_editor.connection.alias

    Person = apps.get_model("core", "Person")

    Person.objects.using(db_alias).update(
        first=models.F("first_name"), middle=models.F("additional_name"), last=models.F("last_name")
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_make_group_short_name_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first', 'last'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='person',
            name='first',
            field=models.CharField(blank=True, max_length=100, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='person',
            name='full',
            field=models.CharField(default='', max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
        migrations.RunPython(
            rewrite_names
        ),
        migrations.RemoveField(
            model_name='person',
            name='additional_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
