# Generated by Django 3.0.4 on 2020-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_make_group_short_name_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Short name of group'),
        ),
    ]
