# Generated by Django 3.0.4 on 2020-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_increase_length_of_group_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='import_ref',
        ),
        migrations.RemoveField(
            model_name='person',
            name='import_ref',
        ),
    ]
