# Generated by Django 3.2.4 on 2021-07-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pdf_file_person_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='school_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.schoolterm', verbose_name='Zugeordnetes Schuljahr'),
        ),
    ]
