# Generated by Django 3.0.5 on 2020-04-13 15:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_incease_length_of_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Title of type')),
                ('description', models.TextField(unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Group type',
                'verbose_name_plural': 'Group types',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='core.GroupType', verbose_name='Type of group'),
        ),
    ]
