# Generated by Django 3.0.5 on 2020-04-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_group_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayWidget',
            fields=[
                ('dashboardwidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.DashboardWidget')),
                ('days', models.IntegerField(default=1, verbose_name='Time span in days')),
            ],
            options={
                'verbose_name': 'Birthday widget',
            },
            bases=('core.dashboardwidget',),
        ),
    ]
