# Generated by Django 3.0.5 on 2020-04-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_group_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('view_address', 'Can view address'), ('view_contact_details', 'Can view contact details'), ('view_photo', 'Can view photo'), ('view_personal_details', 'Can view personal details'), ('view_person_groups', 'Can view persons groups')), 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
