# Generated by Django 3.0.5 on 2020-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_group_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='person',
            name='longtitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longtitude'),
        ),
    ]
