# Generated by Django 3.0.5 on 2020-04-26 15:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_globalpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title of field')),
                ('field_type', models.CharField(choices=[('booleanfield', 'BooleanField'), ('charfield', 'CharField'), ('datefield', 'DateField'), ('datetimefield', 'DateTimeField'), ('decimalfield', 'DecimalField'), ('emailfield', 'EmailField'), ('floatfield', 'FloatField'), ('Integerfield', 'IntegerField'), ('ipaddressfield', 'IPAddressField'), ('genericipaddressfield', 'GenericIPAddressField'), ('nullbooleanfield', 'NullBooleanField'), ('textfield', 'TextField'), ('timefield', 'TimeField'), ('urlfield', 'URLField')], max_length=50, verbose_name='Type of field')),
            ],
            options={
                'verbose_name': 'Addtitional field',
                'verbose_name_plural': 'Addtitional fields',
            },
        ),
        migrations.CreateModel(
            name='PersonGroupThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdditionalField')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='additional_fields',
            field=models.ManyToManyField(through='core.PersonGroupThrough', to='core.AdditionalField'),
        ),
    ]
