# Generated by Django 3.2.9 on 2021-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_person_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, help_text='This is a picture or an avatar for public display.', null=True, upload_to='', verbose_name='Display picture / Avatar'),
        ),
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, help_text='This is an official photo, used for official documents and for internal use cases.', null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, help_text='This is a picture or an avatar for public display.', null=True, upload_to='', verbose_name='Display picture / Avatar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='This is an official photo, used for official documents and for internal use cases.', null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
