# Generated by Django 3.2.9 on 2021-12-09 14:56

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_update_photo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar_rect',
            field=image_cropping.fields.ImageRatioField('photo', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar rect'),
        ),
        migrations.AddField(
            model_name='group',
            name='avatar_square',
            field=image_cropping.fields.ImageRatioField('photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar square'),
        ),
        migrations.AddField(
            model_name='group',
            name='photo_rect',
            field=image_cropping.fields.ImageRatioField('photo', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='photo rect'),
        ),
        migrations.AddField(
            model_name='group',
            name='photo_square',
            field=image_cropping.fields.ImageRatioField('photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='photo square'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_rect',
            field=image_cropping.fields.ImageRatioField('photo', '600x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar rect'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_square',
            field=image_cropping.fields.ImageRatioField('photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar square'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_rect',
            field=image_cropping.fields.ImageRatioField('photo', '600x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='photo rect'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_square',
            field=image_cropping.fields.ImageRatioField('photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='photo square'),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='This is an official photo, used for official documents and for internal use cases.', null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='This is an official photo, used for official documents and for internal use cases.', null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
