# Generated by Django 3.2.10 on 2021-12-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_group_school_term'),
        ('core', '0028_char_field_not_null'),
    ]

    operations = [
    ]
