# Generated by Django 3.2.10 on 2021-12-25 10:59

import aleksis.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField(default=dict, verbose_name='Additional attributes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_attributes', to=settings.AUTH_USER_MODEL, verbose_name='Linked user')),
            ],
            bases=(models.Model, aleksis.core.mixins.PureDjangoModel),
        ),
    ]
